version: "3.8"

networks:
  ethnetwork:
    external: true

services:
  rootless-cni-infra:
    image: quay.io/libpod/rootless-cni-infra:5-amd64
    container_name: rootless-cni-infra
    restart: unless-stopped
    networks:
      - ethnetwork
    command: sleep infinity

  reth:
    image: ghcr.io/paradigmxyz/reth:v1.3.4
    container_name: reth
    restart: unless-stopped
    depends_on:
      - rootless-cni-infra
    networks:
      - ethnetwork
    volumes:
      - rethdata:/root/.local/share/reth/mainnet
      - rethlogs:/root/logs
      - ./jwt.hex:/root/jwt/jwt.hex:ro
    ports:
      - "9011:9011"
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
      - "8551:8551"
    command: >
      node --full --chain=mainnet --metrics 0.0.0.0:9011
      --log.file.directory /root/logs --authrpc.addr 0.0.0.0
      --authrpc.port 8551 --authrpc.jwtsecret /root/jwt/jwt.hex
      --http --http.addr 0.0.0.0 --http.port 8545 --http.api eth,net,web3

  lighthouse:
    image: docker.io/sigp/lighthouse:v7.0.1
    container_name: lighthouse
    restart: unless-stopped
    depends_on:
      - rootless-cni-infra
      - reth
    networks:
      - ethnetwork
    volumes:
      - lighthousedata:/root/.lighthouse
      - ./jwt.hex:/root/jwt/jwt.hex:ro
    ports:
      - "5052:5052"
      - "5053:5053"
      - "5054:5054"
      - "9000:9000"
      - "9000:9000/udp"
      - "9001:9001/udp"
    command: >
      lighthouse bn --network mainnet --http --http-address 0.0.0.0
      --execution-endpoint http://reth:8551 --metrics
      --metrics-address 0.0.0.0 --execution-jwt /root/jwt/jwt.hex
      --log-color --checkpoint-sync-url https://beaconstate-mainnet.chainsafe.io

